# Numpy

In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3,4,5])
print(a**2)

[ 1  4  9 16 25]


从列表传入

In [11]:
l = [0,2,4,6,8]
b = np.array(l)
b

array([0, 2, 4, 6, 8])

生成全0,全1数组

In [21]:
a1 = np.zeros(5,dtype='int')
a2 = np.ones(7,dtype='bool')
print(a1,a2)

[0 0 0 0 0] [ True  True  True  True  True  True  True]


fill 方法  与数据格式转换

In [33]:
a3 = np.array([1,2,3,4],dtype='int')
print(a3)
a3.fill(2.5)
print(a3)
a3 = a3.astype('float')
a3.fill(2.5)
print(a3)

[1 2 3 4]
[2 2 2 2]
[2.5 2.5 2.5 2.5]


In [36]:
a4 = np.arange(1,10) #左闭右开的区间
a4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a5 = np.arange(1,233,3)
a5

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115,
       118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148, 151, 154,
       157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193,
       196, 199, 202, 205, 208, 211, 214, 217, 220, 223, 226, 229, 232])

In [39]:
ob = np.array([21000,21800,22240,23450,25000])
result = ob[1:]-ob[:-1]
result

array([ 800,  440, 1210, 1550])

In [50]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [10,20,30,40,50]])
cc = arr[0:3,2:4].copy() #切片的本质是引用，需要通过copy开辟新的区域
cc

array([[ 3,  4],
       [ 8,  9],
       [30, 40]])

In [65]:
mm = np.array(
    [[0,1,1,1,0],
     [5,4,0,0,1],
     [1,5,6,0,9]]
     ,dtype=bool)
print(arr[mm])
print(arr[(0,1,2),(0,2,4)]) #其实就是对应坐标，不过把x写一起，y写一起
print(arr[:,[0,2,4]])

[ 2  3  4  6  7 10 10 20 30 50]
[ 1  8 50]
[[ 1  3  5]
 [ 6  8 10]
 [10 30 50]]
